// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvEcib-5VcE6uHZVaurLNvp4pJyBOHkWw',
    appId: '1:803188197973:web:77418fc1087b23ea59a2dc',
    messagingSenderId: '803188197973',
    projectId: 'cnergico-connect',
    authDomain: 'cnergico-connect.firebaseapp.com',
    databaseURL: 'https://cnergico-connect-default-rtdb.firebaseio.com',
    storageBucket: 'cnergico-connect.appspot.com',
    measurementId: 'G-9NZ1XMQ69L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvw2KPkdEVBxxN8F9OQINwdZsXexg01FI',
    appId: '1:803188197973:android:b77e8d7b65feaf1a59a2dc',
    messagingSenderId: '803188197973',
    projectId: 'cnergico-connect',
    databaseURL: 'https://cnergico-connect-default-rtdb.firebaseio.com',
    storageBucket: 'cnergico-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDo14NDR5XTJ95AzymXPHRyVvgYuW0nTw',
    appId: '1:803188197973:ios:5d8ce6f9e6ca1e7459a2dc',
    messagingSenderId: '803188197973',
    projectId: 'cnergico-connect',
    databaseURL: 'https://cnergico-connect-default-rtdb.firebaseio.com',
    storageBucket: 'cnergico-connect.appspot.com',
    iosClientId: '803188197973-njqvfdjjhga2ut9ubbmr9blp6ekig1ag.apps.googleusercontent.com',
    iosBundleId: 'com.p2p.cnergyico.cnergyico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDo14NDR5XTJ95AzymXPHRyVvgYuW0nTw',
    appId: '1:803188197973:ios:5d8ce6f9e6ca1e7459a2dc',
    messagingSenderId: '803188197973',
    projectId: 'cnergico-connect',
    databaseURL: 'https://cnergico-connect-default-rtdb.firebaseio.com',
    storageBucket: 'cnergico-connect.appspot.com',
    iosClientId: '803188197973-njqvfdjjhga2ut9ubbmr9blp6ekig1ag.apps.googleusercontent.com',
    iosBundleId: 'com.p2p.cnergyico.cnergyico',
  );
}
